In [20]:
import pandas as pd

solar_data = pd.read_csv('C:/Users/ilyad/IDE/study/python_final/solarpower.csv')
solar_data

           date  cum_power
0    2017-01-01    20111.0
1    2017-01-02    20112.0
2    2017-01-03    20115.0
3    2017-01-04    20117.0
4    2017-01-05    20119.0
..          ...        ...
659  2018-10-22    28101.0
660  2018-10-23    28109.0
661  2018-10-24    28115.0
662  2018-10-25    28117.0
663  2018-10-26    28120.0

[664 rows x 2 columns]

In [23]:
df = pd.DataFrame(solar_data)

date_cols = ["date"]
df[date_cols] = df[date_cols].astype("datetime64[ns]")
df["day_power"] = df["date"].dt.to_period("M")
df

          date  cum_power day_power
0   2017-01-01    20111.0   2017-01
1   2017-01-02    20112.0   2017-01
2   2017-01-03    20115.0   2017-01
3   2017-01-04    20117.0   2017-01
4   2017-01-05    20119.0   2017-01
..         ...        ...       ...
659 2018-10-22    28101.0   2018-10
660 2018-10-23    28109.0   2018-10
661 2018-10-24    28115.0   2018-10
662 2018-10-25    28117.0   2018-10
663 2018-10-26    28120.0   2018-10

[664 rows x 3 columns]

In [26]:
df["day_power"]['2017-03'] = df.mean(axis=2)

ValueError: No axis named 2 for object type DataFrame